Ableton/python-pipeline-utils

- vars/virtualenv.groovy
> Add singleton for virtualenv

- vars/virtualenv.groovy
This PR is in response to @ala-ableton's comments on https://github.com/AbletonDevTools/python-pipeline-utils/pull/1. ptal @AbletonDevTools/gotham-city, thanks!
> Various cleanups to virtualenv library

- Jenkinsfile
- src/com/ableton/VirtualEnv.groovy
ping @AbletonDevTools/gotham-city, thanks!
> Add Jenkinsfile to repo

- Jenkinsfile
ptal @AbletonDevTools/gotham-city , thanks!
> Use version 0.2.0 of codenarc library

- Jenkinsfile
- build.gradle
- src/com/ableton/VirtualEnv.groovy
- test/com/ableton/JenkinsMocks.groovy
- test/com/ableton/JenkinsMocksTest.groovy
- test/com/ableton/VirtualEnvTest.groovy
- test/resources/EmptyPipeline.groovy
Related to https://github.com/AbletonAppDev/devtools/issues/856, ptal @AbletonDevTools/gotham-city, thanks!
> Update to codenarc 0.5.0

- Jenkinsfile
- README.md
> Add README

- build.gradle
ping @AbletonDevTools/gotham-city, thanks!
> Compile files in the vars directory

- Jenkinsfile
Related to https://github.com/AbletonAppDev/devtools/issues/868, ping @AbletonDevTools/gotham-city
> Migrate to latest shared pipeline libraries

- Jenkinsfile
- src/com/ableton/VirtualEnv.groovy
- test/com/ableton/VirtualEnvTest.groovy
- test/resources/EmptyPipeline.groovy
- vars/virtualenv.groovy
> Update to groovylint 0.2.0

- src/com/ableton/VirtualEnv.groovy
- test/com/ableton/VirtualEnvTest.groovy
> Allow absolute python paths in VirtualEnv constructor

- Jenkinsfile
> Update Jenkinsfile libraries, minor fix to junit execution

- Jenkinsfile
ping @AbletonDevTools/gotham-city
> Update to ableton-utils 0.6.0

- vars/pythonBuilder.groovy
> Add script argument in pythonBuilder singleton

- src/com/ableton/PythonBuilder.groovy
- test/com/ableton/PythonBuilderTest.groovy
> Add option to PythonBuilder to build with ccache

- Jenkinsfile
> Update to ableton-utils 0.6.4

- Jenkinsfile
- src/com/ableton/PythonBuilder.groovy
- src/com/ableton/VirtualEnv.groovy
- src/com/ableton/VirtualEnvList.groovy
- vars/pythonBuilder.groovy
- vars/virtualenv.groovy
- vars/virtualenvs.groovy
> Add groovydoc for missing methods/classes, publish docs from Jenkins

- CONTRIBUTING.md
ping @AbletonDevTools/gotham-city
> Add CONTRIBUTING file to repository

- test/com/ableton/VirtualEnvTest.groovy
@mst-ableton, @nre-ableton, @rco-ableton: please review, thanks!
> Remove obsolete warning suppression decorator

- Jenkinsfile
- build.gradle
- test/com/ableton/PipenvTest.groovy
- test/com/ableton/PythonPackageTest.groovy
- test/com/ableton/VirtualEnvTest.groovy
Related to https://github.com/AbletonAppDev/devtools/issues/2999
> Update JenkinsPipelineUnit to 1.7

- Jenkinsfile
- Bump ableton-utils to 0.21
- Bump groovylint to 0.12
> Bump pipeline libraries to latest versions

- build.gradle
- test/com/ableton/PipenvTest.groovy
- test/com/ableton/PythonPackageTest.groovy
- test/com/ableton/VirtualEnvTest.groovy
- Bump groovy-all to 2.4.14
- Use testImplementation instead of testCompile
- Update to JUnit 5
> Update to JUnit 5

- src/com/ableton/VirtualEnv.groovy
- test/com/ableton/VirtualEnvTest.groovy
These cleanups are in preparation for a larger refactoring. I've made a separate PR so that the subsequent one will be a bit easier to review.
> Various cleanups

- README.md
Just a minor cleanup that I found while looking through the README.
> Add @Library annotation in example code
